export {default as IntroPage} from './intro-page/intro-page'
export {default as DailyBodyCarePage} from './DailyBodyCarePage/DailyBodyCarePage'
export {default as ExplanationPage} from './Explanationpage/ExplanationPage'
export {default as HydratingIngredientsPage} from './HydratingIngredientsPage/HydratingIngredientsPage'
export {default as IssuesPage} from './IssuesPage/IssuesPage'
export {default as MoisturizePage} from './MoisturizePage/MoisturizePage'
export {default as ProblemAreaPage} from './ProblemAreaPage/ProblemAreaPage'
export {default as SkinPage} from './SkinPage/SkinPage'